# Generated by Django 4.1.4 on 2022-12-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
